# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # --- General ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^src/orchestration/tsconfig\.json$
      - id: check-added-large-files
      - id: check-merge-conflict

  # --- Security ---
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

  # --- Terraform ---
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
        args: [--args=-recursive]
      - id: terraform_validate
        # remove the --no-cache line
        require_serial: true
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'

  # --- Python format/lint ---
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --expand-star-imports
        files: ^src/.*\.py$

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
        args: [--line-length=88]
        files: ^src/.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
        files: ^src/.*\.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        files: ^src/.*\.py$
        args:
          - "--max-line-length=100"
          - "--ignore=E203,W503"

  # --- Python (auto-remove unused imports first) ---
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --expand-star-imports
        files: ^src/.*\.py$

  # --- Node / TypeScript / JSON / YAML ---
  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: v3.4.2
    hooks:
      - id: prettier
        files: '\.(js|jsx|ts|tsx|json|md|ya?ml|css|html)$'
        exclude: ^infra/
        additional_dependencies:
          - prettier@3.4.2
          # add plugins here if you use them, e.g.:
          # - '@prettier/plugin-xml@3.4.2'
