# Configuration for the 'staging' environment
environment: staging

# Logging configuration
logging:
  level: "INFO" # Less verbose than DEBUG, focuses on informational events
  powertools_service_name: "event-forge-staging"

# AWS specific configuration
aws:
  region: "us-east-1"
  s3:
    assets_bucket_name: "event-forge-assets-staging"
    outputs_bucket_name: "event-forge-outputs-staging"
  dynamodb:
    sheet_watch_table: "SheetWatchRegistry-staging"
  secrets_manager:
    adobe_api_key_name: "event-forge/adobe-api-key-staging"
    google_credentials_name: "event-forge/google-wif-config-staging"

# Inngest configuration
inngest:
  main_trigger_event: "google/drive.sheet.updated"
  generate_event_name: "poster/generate.request"

# Adobe API configuration
adobe:
  # Higher concurrency for staging to test performance
  concurrency_limit: 50
  # Polling interval for checking job status
  polling_interval_seconds: 10

# Google configuration
google:
  # This is the static URL for the Inngest endpoint that Google will call
  # This will be populated from Terraform outputs
  ingest_webhook_url: "https://cloud.inngest.com/api/v1/e/YOUR_EVENT_KEY" # Placeholder